### ISSUE TITLE
Stickman dosent attack Carminite Ghast

### ISSUE THREAD

**Issue by ForceerGames** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#10]
**Describe the bug**
Stickman would not attack Carminite Ghasts

**To Reproduce**
1. Spawn stickman with any Carminite Ghast

**Expected behavior**
Stickman should attack Carminite Ghasts

**TNT and Disparity Mod Details**
- Mod Version: Alpha 0.4.1 Build 621 Pre-Integration Test

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A10
 - OS: Android 10
 - Browser Chrome
 - Version: 10.0

**Comment by Pechayland** [comment]
Please wait for the next Pre-Integration Test

**Comment by ForceerGames** [comment]
Ok
