### ISSUE TITLE
Ekoring DLK King Spawns Too Many DLKs and Causes my Game to Lag

### ISSUE THREAD

**Issue by Pechayland** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#11]
**Describe the bug**
When Ekored DLK King spawns thousands of DLKs.

**To Reproduce**
1. Attack the DLK King with Ekors.

**Expected behavior**
It should not spawn that much DLKs.

**Screenshots**
![2021-08-01_16 54 42](https://user-images.githubusercontent.com/65995040/127765378-e1234cd4-18a7-490d-bd64-90d90e7b1a5f.png)

**TNT and Disparity Mod Details**
- Mod Version: Alpha 0.4.1 Build 623 Pre-Integration Test

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 22000.100

**Comment by Burnuts** [comment]
@Pechayland forgot to label this issue after creating it.
