### ISSUE TITLE
Sticky Achievement won't load in Minecraft.

### ISSUE THREAD

**Issue by GhastCreepypasta** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#13]
**Describe the bug**
It will make the achievement unobtainable.
[20:25:01] [Render thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading custom advancement tnt_and_disparity:sticky: Expected item to be an item, was unknown string 'tnt_and_disparity:glue_water'

**To Reproduce**
1. Launch Minecraft.
2. See log.

**Expected behavior**
It should successfully load the achievement.

**TNT and Disparity Mod Details**
- Mod Version: Alpha 0.4.1 Build 626 Pre-Integration Test (Will you accept custom built because I'm fixing your structure generation issue?)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 21H1

**Comment by Pechayland** [comment]
Thanks but ive done it. But I will fix this.

**Comment by Pechayland** [comment]
I think I fixed it @GhastCreepypasta but I have to see if it's there first.

**Comment by PechayClub** [comment]
Silly Unfixable Issue.

**Comment by aaronschneider7797** [comment]
Maybe we could fix it?
