### ISSUE TITLE
Building Problem With MCreator 2021.2 Snapshot

### ISSUE THREAD

**Issue by ForceerGames** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#2]
When we build it Using MCreator 2021.2 Snapshot it fails

1. Open MCreator 2021.2 Snapshot
2. Open the Project
3. Build

We got this log.
Executing 
    Gradle task: eclipse

Build 
    info: MCreator 2021.2.23417 EAP (23417), forge-1.16.5, 64-bit, 16335 MB, 
    Windows 10, JVM 11.0.11, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk

FAILURE: 
    Build failed with an exception.

* 
    What went wrong:

Could 
    not create an instance of type org.gradle.invocation.DefaultGradle.

> 
    Could not configure services using GradleScopeCompileServices.configure().

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

BUILD 
    FAILED in 2s

BUILD 
    FAILED

Task 
    completed in 2 seconds

**Comment by Azar2477** [comment]
For me also when I build it too so I have to use MCreator 2021.1 instead.

I will report this issue to MCreator Github.

**Comment by Azar2477** [comment]
It's a MCreator Issue and you need to wait for the next snapshot.

**Comment by Pechayland** [comment]
There is a new snapshot guys but I have to test it.

**Comment by Azar2477** [comment]
It's fixed.
