### ISSUE TITLE
Stickman Spawn spawns Stickman at z ~ y ~-1  z ~

### ISSUE THREAD

**Issue by Pechayland** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#4]
Stickman Spawn spawns Stickman at z ~ y ~-1  z ~ and it will crush them in one spot.

**Comment by Pechayland** [comment]
It cannot be fixed.

**Comment by Azar2477** [comment]
Cannot be fixed.

**Comment by Pechayland** [comment]
We will not lock this however, but will you help us out how to solve this issue.
