### ISSUE TITLE
Defective Update JSON File

### ISSUE THREAD

**Issue by Azar2477** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#8]
**Describe the bug**
There is no sign that the mod needs to update.

**To Reproduce**
1. Launch Minecraft with the older version of the mod.

**Expected behavior**
It should say the mod needs update.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 10.0.22000.100

**Comment by Pechayland** [comment]
We might need to edit one of the base mod files.

**Comment by Azar2477** [comment]
Yes @Pechayland

**Comment by Azar2477** [comment]
Still there. Reopening.

**Comment by Pechayland** [comment]
It might be a Minecraft Forge issue.

**Comment by Pechayland** [comment]
It's fixed.
