### ISSUE TITLE
DLKs have gone out of control

### ISSUE THREAD

**Issue by Pechayland** [Team-Burnuts/BurnutsPlusTNTandDisparityMod#9]
**Describe the bug**
When I see the DLKs the DLKs start to attack each other and won't attack their targets.

**To Reproduce**
1. Go to DLK Land or spawn 2 DLKs with nearby targets.

**Expected behavior**
DLKs should attack the mobs it targets,

**TNT and Disparity Mod Details**
- Mod Version: Alpha 0.4.1 Build 620 Pre-Integration Test

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 22000.100

**Comment by Burnuts** [comment]
This issue randomly happens when @aaronschneider7797 build and tested the mod.
